module.exports.ERROR_CODE = {
    DEFAULT:400,
    UNAUTHORISE:401,
    FAILED:0,
    EXCEPTION:2, 
    INVALIDREQUEST:3,   
    CONTESTNOTFOUND:4,
    INSUFFICIENTBALANCE:501,
    CLIENT_OUTDATED:5,
    RESYNC:6
}