module.exports = {
     GAME_SEARCH_TIME_SECONDS: 20,
     GAME_SEARCH_TIME_SERVER_SECONDS: 22,
     GAME_TURN_TIME_SECONDS: 25,
     GAME_TURN_TIME_SECONDS_SERVER: 27,
     GAME_EXPIRE_SECONDS: 120000,
     TABLE_WAITING_SECONDS : 120000,
     GAME_START_TIME_AFTER_JOIN : 5000
}